# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [9]:
x = torch.Tensor(5, 3)
print(x)

tensor([[2.4649e-30, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0558, 0.3136, 0.4139],
        [0.7675, 0.4063, 0.2798],
        [0.0031, 0.9826, 0.6654],
        [0.1271, 0.5355, 0.6484],
        [0.6726, 0.4770, 0.0947]])


Get its size

In [10]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [11]:
x[1:3] = 2
print(x)

tensor([[2.4649e-30, 0.0000e+00, 0.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [7]:
x = torch.Tensor(2, 17)
y = torch.FloatTensor(3, 1)
z = torch.LongTensor(5, 2, 1)
z[::] = 7
print(z)
print(x)

k = torch.ByteTensor(5,)
k[1:4] = 1
k[0] = 0
print(k)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
tensor([[2.3833e-30, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.3788e-14, 6.8720e+11,
         2.7253e+20, 3.0866e+29, 2.3506e-30, 0.0000e+00, 2.3822e-44, 0.0000e+00,
         2.3822e-44, 0.0000e+00, 2.7495e+26, 5.6502e-02, 7.1005e-34],
        [0.0000e+00, 5.0447e-44, 0.0000e+00, 5.0447e-44, 0.0000e+00, 1.6795e+08,
         4.7423e+30, 7.0634e-34, 0.0000e+00, 5.0447e-44, 0.0000e+00, 5.0447e-44,
         0.0000e+00, 5.0944e-14, 4.1613e-41, 1.0021e-23, 4.1890e-41]])
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

RuntimeError: The size of tensor a (17) must match the size of tensor b (3) at non-singleton dimension 1

### 2.2 Addition: syntax 2

In [16]:
print(torch.add(x, y))

tensor([[0.4714, 0.5565, 1.0297],
        [2.0957, 2.3864, 2.2943],
        [2.1009, 2.5574, 2.4945],
        [0.6099, 0.5472, 1.6369],
        [1.2125, 0.4981, 1.0102]])


### 2.3 Addition: giving an output tensor

In [17]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.4714, 0.5565, 1.0297],
        [2.0957, 2.3864, 2.2943],
        [2.1009, 2.5574, 2.4945],
        [0.6099, 0.5472, 1.6369],
        [1.2125, 0.4981, 1.0102]])


### 2.4 Addition: in-place

adds `x` to `y`

In [18]:
y.add_(x)
print(y)

tensor([[0.4714, 0.5565, 1.0297],
        [2.0957, 2.3864, 2.2943],
        [2.1009, 2.5574, 2.4945],
        [0.6099, 0.5472, 1.6369],
        [1.2125, 0.4981, 1.0102]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [ ]:
print(x[:, 1])

**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [ ]:
tensor1 = torch.Tensor(2, 4)
tensor2 = torch.Tensor(2, 4)
tensor1[::] = 2
tensor2[::] = 4
print(tensor1)
print(tensor2)
print(torch.Tensor.mul(tensor1, tensor2))
tensor2.mul_(tensor1)
print(tensor2)
tensor3 = torch.Tensor(4, 2)
print(tensor2 @ tensor3)

tensor([[2.4057e-30, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.4017e-30, 0.0000e+00, 7.1248e-34, 0.0000e+00]])
tensor([[2.4092e-30, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.4017e-30, 0.0000e+00, 1.1713e-30, 0.0000e+00]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [29]:
x = torch.ones(5, 2)
y = x.numpy()
z = torch.from_numpy(y)

print(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [30]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
